#!/usr/bin/env php -d display_errors
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Game\PlayCommand;

$app = new Application();


$app->add(new PlayCommand());
$app->run();
