#!/usr/bin/env php -d display_errors
<?php

putenv('APP_ENV=dev');
putenv('APP_DEBUG=1');

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Game\PlayCommand;

$app = new Application();

try {
    $app->add(new PlayCommand());
    $app->run();
} catch(Exception $e){
    echo $e->getMessage();
}